#!/usr/bin/env bash
#
# Generate /opt/wp/compose/.env with a random MARIADB_ROOT_PASSWORD if missing.
# Symlinks /opt/wp/.env to compose/.env so wp-create + the rest of the CLI
# share the same secret source.
#
# Idempotent: re-running does NOT regenerate or overwrite an existing password.
# If you really want to rotate the root password, delete the .env file first
# and re-run — but note that you'll need to ALTER USER inside the running
# wp-mariadb container for the change to take effect.
#

set -euo pipefail

WP_ROOT="${WP_ROOT:-/opt/wp}"
ENV_FILE="$WP_ROOT/compose/.env"
ENV_LINK="$WP_ROOT/.env"

# Must run as root (writes mode-600 file in /opt/wp)
if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    echo "init-secrets.sh must run as root (try: sudo $0)" >&2
    exit 1
fi

# Verify openssl is available
if ! command -v openssl >/dev/null 2>&1; then
    echo "openssl not found — install with: sudo apt install openssl" >&2
    exit 1
fi

# Ensure compose/.env exists and contains a real (non-placeholder) password
if [ -f "$ENV_FILE" ] && grep -qE '^MARIADB_ROOT_PASSWORD=[^[:space:]]' "$ENV_FILE" \
   && ! grep -qE '^MARIADB_ROOT_PASSWORD=replace-with-' "$ENV_FILE"; then
    echo "✓ $ENV_FILE already has a MARIADB_ROOT_PASSWORD set."
    echo "  (Re-run with a deleted file to regenerate.)"
else
    PASSWORD="$(openssl rand -hex 24)"

    if [ -f "$ENV_FILE" ]; then
        # Replace any existing line (including the placeholder) in place
        sed -i.bak -E "s|^MARIADB_ROOT_PASSWORD=.*|MARIADB_ROOT_PASSWORD=${PASSWORD}|" "$ENV_FILE"
        rm -f "${ENV_FILE}.bak"
        echo "✓ Replaced placeholder MARIADB_ROOT_PASSWORD in $ENV_FILE"
    else
        # Bootstrap fresh from .env.example if available, else write a minimal file
        if [ -f "$WP_ROOT/compose/.env.example" ]; then
            cp "$WP_ROOT/compose/.env.example" "$ENV_FILE"
            sed -i.bak -E "s|^MARIADB_ROOT_PASSWORD=.*|MARIADB_ROOT_PASSWORD=${PASSWORD}|" "$ENV_FILE"
            rm -f "${ENV_FILE}.bak"
        else
            cat > "$ENV_FILE" <<EOF
# MultiWordpress shared infrastructure secrets — generated by init-secrets.sh
MARIADB_ROOT_PASSWORD=${PASSWORD}
EOF
        fi
        echo "✓ Generated $ENV_FILE with random MARIADB_ROOT_PASSWORD"
    fi

    chmod 600 "$ENV_FILE"
    chown root:root "$ENV_FILE"
fi

# Symlink /opt/wp/.env → compose/.env so the CLI (wp-create, wp-stats, etc.)
# can find it via $WP_ROOT/.env without operators copying secrets around.
if [ ! -L "$ENV_LINK" ] || [ "$(readlink "$ENV_LINK")" != "$ENV_FILE" ]; then
    ln -sf "$ENV_FILE" "$ENV_LINK"
    echo "✓ Symlinked $ENV_LINK → $ENV_FILE"
else
    echo "✓ Symlink $ENV_LINK already points to $ENV_FILE"
fi

echo ""
echo "Secrets initialized. Next:"
echo "  cd $WP_ROOT && sudo docker compose -f compose/compose.yaml up -d"
